core/urls.py
from django.urls import path

from . views import (
	HomeView,
	ItemDetailView,
	OrderSummaryView,
	add_to_cart,
	remove_from_cart,
	CheckOutView,
	remove_single_item_from_cart,
	PaymentView,
)
app_name = 'core'


urlpatterns = [
	path('',HomeView.as_view(),name="home"),
	path('checkout/',CheckOutView.as_view(),name="checkout"),
	path('product/<slug>/',ItemDetailView.as_view(),name="product"),
	path('order-summary/',OrderSummaryView.as_view(),name="order-summary"),
	path('add-to-cart/<slug>/',add_to_cart,name="add-to-cart"),
	path('remove-from-cart/<slug>/',remove_from_cart,name="remove-from-cart"),
	path('remove-single-item-from-cart/<slug>/',remove_single_item_from_cart,name="remove-single-item-from-cart"),
	path('payment/<payment_option>/', PaymentView.as_view(), name="payment"),
]

ecommerce_pro/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace = 'core'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField




CATEGORY_CHOICES = (
	('S','Shirt'),
	('SW','Sport wear'),
	('OW','Outwear')
)


LABEL_CHOICES = (
	('P','primary'),
	('S','secondary'),
	('D','danger')
)



class Item(models.Model):
	title = models.CharField(max_length=100)
	price = models.FloatField()
	discount_price = models.FloatField(blank=True,null=True)
	category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
	label = models.CharField(choices=LABEL_CHOICES, max_length=1)
	slug = models.SlugField()
	description = models.TextField()
	image = models.ImageField(blank=True, null=True)
	quantity = models.IntegerField(default=1)


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("core:product", kwargs={
			'slug':self.slug
		})
	

	def get_add_to_cart_url(self):
		return reverse("core:add-to-cart", kwargs={
			'slug':self.slug,
		})
	def get_remove_from_cart_url(self):
		return reverse("core:remove-from-cart", kwargs={
			'slug':self.slug
		})



class OrderItem(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	ordered = models.BooleanField(default=False)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	
	def __str__(self):
		return f"{self.quantity} of {self.item.title}"

	def get_total_item_price(self):
		return self.quantity * self.item.price

	def get_total_discount_item_price(self):
		return self.quantity * self.item.discount_price

	def get_amount_saved(self):
		return self.get_total_item_price() - self.get_total_discount_item_price()

	def get_final_price(self):
		if self.item.discount_price:
			return self.get_total_discount_item_price()
		return self.get_total_item_price()


class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	ordered = models.BooleanField(default=False)
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField()
	items = models.ManyToManyField(OrderItem)
	billing_address = models.ForeignKey('BillingAddress',
		on_delete=models.SET_NULL, blank=True, null=True)
	payment = models.ForeignKey('Payment',
		on_delete=models.SET_NULL, blank=True, null=True)



	def __str__(self):
		return self.user.username


	def get_total(self):
		total = 0
		for order_item in self.items.all():
			total += order_item.get_final_price()
		return total


class BillingAddress(models.Model):
	user  = models.ForeignKey(settings.AUTH_USER_MODEL,
			on_delete=models.CASCADE)
	street_address = models.CharField(max_length=100)
	apartment_address = models.CharField(max_length=100)
	country = CountryField(multiple=False)
	zip = models.CharField(max_length=100)
	


	def __str__(self):
		return self.user.username



class Payment(models.Model):
	stripe_charge_id = models.CharField(max_length=50)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
	amount = models.FloatField()
	timestamp = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.user.username

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget



PAYMENT_CHOICES = (
	('S', 'Stripe'),
	('P','PayPal'),
)

class CheckOutForm(forms.Form):
	street_address = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder':'Plot 56 kalmax Building,Bombo Road'
	}))
	apartment_address = forms.CharField(required=False, widget=forms.TextInput(
		attrs={ 'placeholder':'Apartment or Suite' }))
	country = CountryField(blank_label='(select country)').formfield(
			widget = CountrySelectWidget(attrs={
				'class':'custom-select d-block w-100'
				})
		)
	zip = forms.CharField(widget=forms.TextInput(attrs={
		'class':'form-control',
		'placeholder': 'Zip Code'
		}))
	same_shipping_address = forms.BooleanField(required=False)
	save_info = forms.BooleanField(required=False)
	payment_option = forms.ChoiceField(
		widget=forms.RadioSelect(),choices=PAYMENT_CHOICES)

core/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import ListView,DetailView,View
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from . models import Item,OrderItem,Order,BillingAddress, Payment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from .forms import CheckOutForm


import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

# `source` is obtained with Stripe.js; see https://stripe.com/docs/payments/accept-a-payment-charges#web-create-token






class HomeView(ListView):
	model = Item
	paginate_by = 10
	template_name = "home.html"

class CheckOutView(View):
	def get(self, *args, **kwargs):
		# forms
		form = CheckOutForm()
		context = {
			"form":form,
		}
		return render(self.request, "checkout.html", context)

	def post(self, *args, **kwargs):
		form = CheckOutForm(self.request.POST or None)
		try:
			order = Order.objects.get(user=self.request.user, ordered=False)
			if form.is_valid():
				street_address = form.cleaned_data.get('street_address')
				apartment_address = form.cleaned_data.get('apartment_address')
				country =  form.cleaned_data.get('country')
				# TODO
				# same_shipping_address = form.cleaned_data.get('same_shipping_address')
				# save_info = form.cleaned_data.get('save_info')
				payment_option = form.cleaned_data.get('payment_option')
				billing_address = BillingAddress(
					user=self.request.user,
					street_address=street_address,
					apartment_address=apartment_address,
					country=country,
					zip=zip,
				)
				billing_address.save()
				order.billing_address = billing_address
				order.save()

				if payment_option == 'S':
					return redirect('core:payment', payment_option='stripe')
				elif payment_option == 'P':
					return redirect('core:payment', payment_option='paypal')
				else:
					messages.warning(self.request,"Invalid Payment Option Selected")
				# ToDO add a redirect to the selected payment option
				return redirect("core:checkout")
			messages.warning(self.request,"Failed Checkout")
			return redirect("core:checkout")

		except ObjectDoesNotExist:
			messages.warning(self.request, "You do not have an active order")
			return redirect("core:order-summary")

class PaymentView(View):
	def get(self, *args, **kwargs):
		# order
		order = Order.objects.get(user=self.request.user,ordered=False)
		context ={
			'order':order,
		}
		return render(self.request, "payment.html", context)

	def post(self, *args, **kwargs):
		# order
		order = Order.objects.get(user=self.request.user,ordered=False)
		token = self.request.POST.get('stripeToken')
		amount = int(order.get_total() * 100) # * 100 because of cents

		try:
			charge = stripe.Charge.create(
				amount=amount, 
				currency="usd",
				source=token,
				description="My First Test Charge",
			)


			# create the payment

			payment = Payment()
			payment.stripe_charge_id = charge['id']
			payment.user = self.request.user
			payment.amount = order.get_total()
			payment.save()
			print(amount)

			# assign payment to order
			order.payment = True
			order.payment = payment
			order.save()
			messages.success(self.request, "Your order was successful")
			return redirect("/")

		except stripe.error.CardError as e:
			body = e.json_body
			err = body.get('error', {})

			messages.error(self.request, f"{err.get('message')}")
			return redirect("/")

		except stripe.error.RateLimitError as e:
			# Too many requests made to the API too quickly
			messages.error(self.request, "Rate RateLimitError")
			return redirect("/")
			
		except stripe.error.InvalidRequestError as e:
			# Invalid parameters were supplied to Stripe's API
			messages.error(self.request,"Invalid parameters")
			return redirect("/")
			
		except stripe.error.AuthenticationError as e:

			# Authentication with Stripe's API failed
			# (maybe you changed API keys recently)
			messages.error(self.request, "Not Authenticated")
			return redirect("/")
			
		except stripe.error.APIConnectionError as e:
			# Network communication with Stripe failed
			messages.error(self.request, "Network error")
			return redirect("/")
		
		except stripe.error.StripeError as e:
			# Display a very generic error to the user, and maybe send
			# yourself an email
			messages.error(self.request, "Something went wrong. You were not charged")
			return redirect("/")
			
		except Exception as e:
			# Send an Email
			messages.error(self.request, "Serious Error occured")
			print(e)
			return redirect("/")


class ItemDetailView(DetailView):
	model = Item
	template_name = "product.html"

class OrderSummaryView(LoginRequiredMixin, View):
	def get(self, *args, **kwargs):
		try:
			order = Order.objects.get(user=self.request.user, ordered=False)
			context = {
				'object': order
				}
			return render(self.request, 'order_summary.html', context)
		except ObjectDoesNotExist:
			messages.warning(self.request, "You do not have an active order")
			return redirect("/")
		
	

@login_required
def add_to_cart(request,slug):
	item = get_object_or_404(Item,slug=slug)
	order_item, created= OrderItem.objects.get_or_create(
		item=item,
		user=request.user,
		ordered=False)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		# check if order item is in the order
		if order.items.filter(item__slug=item.slug).exists():
			order_item.quantity += 1
			order_item.save()
			messages.info(request, "This item quantity was updated to cart")
			return redirect("core:order-summary")
		else:
			order.items.add(order_item)
			messages.info(request, "This item was added to your cart")
			return redirect("core:order-summary")
	else:
		ordered_date = timezone.now()
		order = Order.objects.create(user=request.user,ordered_date=ordered_date)
		order.items.add(order_item)
		messages.info(request, "This item was added to your cart")
		return redirect("core:order-summary")


@login_required
def remove_from_cart(request,slug):
	item = get_object_or_404(Item,slug=slug)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		# check if order item is in the order
		if order.items.filter(item__slug=item.slug).exists():
			order_item = OrderItem.objects.filter(
				item=item,
				user=request.user,
				ordered=False
			)[0]
			order.items.remove(order_item)
			order_item.delete()
			messages.info(request, "This item was removed to cart")
			return redirect("core:product",slug=slug)
		else:
			#add message saying the user does not have an order
			messages.info(request, "This item was not in your cart")
			return redirect("core:product",slug=slug)
	else:
		#add message saying the user does not have an order
		messages.info(request, "You don't have an active order")
		return redirect("core:product", slug=slug)
		
@login_required
def remove_single_item_from_cart(request,slug):
	item = get_object_or_404(Item,slug=slug)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		# check if order item is in the order
		if order.items.filter(item__slug=item.slug).exists():
			order_item = OrderItem.objects.filter(
				item=item,
				user=request.user,
				ordered=False
			)[0]
			if order_item.quantity > 1:
				order_item.quantity -= 1
				order_item.save()
			else:
				order.item.remove(order_item)
			messages.info(request, "This item was updated")
			return redirect("core:order-summary")
		else:
			#add message saying the user does not have an order
			messages.info(request, "This item was not in your cart")
			return redirect("core:product",slug=slug)
	else:
		#add message saying the user does not have an order
		messages.info(request, "You don't have an active order")
		return redirect("core:product",slug=slug)

core/templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
            {% csrf_token %}

              <!--address-->
              <div class="md-form mb-5">
                <!-- <input type="text" id="address" class="form-control" placeholder="1234 Main St"> -->
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                <!-- <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite"> -->
                {{ form.apartment_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  <!-- <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select> -->

                  {{form.country}}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  <!-- <input type="text" class="form-control" id="zip" placeholder="" required> -->
                  {{form.zip}}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input {% if form.same_shipping_address.value %} checked {% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input {% if form.save_info.value %} checked {% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{value}}" type="radio" class="custom-control-input" required> 
                 
                  <label class="custom-control-label" for="{{name}}">{{name}}</label>
                </div>
                {% endfor %}
               
              </div>


            
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->




        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->




      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

 {% endblock %}

core/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <div class="container">

      <!--Navbar-->
      
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
        	{% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                  <img src="{{item.image.url}}" class="card-img-top">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{item.get_absolute_url }}" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">

                    {{item.title}}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>
                  	{% if item.discount_price %}
                  		{{ item.discount_price }}UGX
                  	{% else %}
                  		{{item.price}}UGX
                  	{% endif %}
                  	</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
        {% endif %}
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>

{% endblock content %}

core/templates/order_summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <div class="table-responsive text-nowrap">
      <h2>Order Summary</h2>
      <table class="table align-middle">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Item title</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Item Price</th>
        </tr>
      </thead>
      <tbody>
        {% for order_item in object.items.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{order_item.item.title}}</td>
          <td>{{order_item.item.price}}</td>
          <td><a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>{{order_item.quantity}}<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a></td>
          <td>
            {% if order_item.item.discount_price %}
              UGX {{ order_item.get_total_discount_item_price }}
              <span class="badge bg-primary">Saving UGX{{order_item.get_amount_saved }}</span>
            {% else %}
              UGX {{ order_item.get_total_item_price }}
            {% endif %}
            <a style="color: red;" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
        </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">Your cart is Empty</td>
        </tr>
        <tr>
          <td colspan="5">
            <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
          </td>
        </tr>
        {% endfor %}
        {% if object.get_total %}
        <tr>
          <td colspan="4"><b>Order Total</b></td>
          <td colspan="5"><b>UGX{{object.get_total }}</b></td>
        </tr>

        <tr>
          
          <td colspan="5">
            <a class="btn btn-warning float-right ml-2" href="/checkout/">Proceed to Checkout</a>
            <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
          </td>
        </tr>
        {% endif %}
      </tbody>
</table>





    </div>
  </main>

{% endblock content %}

core/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              
              
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <del>{{ object.price }}</del>
                <span class="mr-1">
                    {{ object.discount_price }}UGX   
                </span>
              {% else %}
                <span>{{object.price}}</span>  
              {% endif %}
                
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <!-- <form class="d-flex justify-content-left">
              
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> -->
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p" >Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p" >Remove From Cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %} 